require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HaikusController do

  # This should return the minimal set of attributes required to create a valid
  # Haiku. As you add validations to Haiku, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all haikus as @haikus" do
      haiku = Haiku.create! valid_attributes
      get :index
      assigns(:haikus).should eq([haiku])
    end
  end

  describe "GET show" do
    it "assigns the requested haiku as @haiku" do
      haiku = Haiku.create! valid_attributes
      get :show, :id => haiku.id
      assigns(:haiku).should eq(haiku)
    end
  end

  describe "GET new" do
    it "assigns a new haiku as @haiku" do
      get :new
      assigns(:haiku).should be_a_new(Haiku)
    end
  end

  describe "GET edit" do
    it "assigns the requested haiku as @haiku" do
      haiku = Haiku.create! valid_attributes
      get :edit, :id => haiku.id
      assigns(:haiku).should eq(haiku)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Haiku" do
        expect {
          post :create, :haiku => valid_attributes
        }.to change(Haiku, :count).by(1)
      end

      it "assigns a newly created haiku as @haiku" do
        post :create, :haiku => valid_attributes
        assigns(:haiku).should be_a(Haiku)
        assigns(:haiku).should be_persisted
      end

      it "redirects to the created haiku" do
        post :create, :haiku => valid_attributes
        response.should redirect_to(Haiku.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved haiku as @haiku" do
        # Trigger the behavior that occurs when invalid params are submitted
        Haiku.any_instance.stub(:save).and_return(false)
        post :create, :haiku => {}
        assigns(:haiku).should be_a_new(Haiku)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Haiku.any_instance.stub(:save).and_return(false)
        post :create, :haiku => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested haiku" do
        haiku = Haiku.create! valid_attributes
        # Assuming there are no other haikus in the database, this
        # specifies that the Haiku created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Haiku.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => haiku.id, :haiku => {'these' => 'params'}
      end

      it "assigns the requested haiku as @haiku" do
        haiku = Haiku.create! valid_attributes
        put :update, :id => haiku.id, :haiku => valid_attributes
        assigns(:haiku).should eq(haiku)
      end

      it "redirects to the haiku" do
        haiku = Haiku.create! valid_attributes
        put :update, :id => haiku.id, :haiku => valid_attributes
        response.should redirect_to(haiku)
      end
    end

    describe "with invalid params" do
      it "assigns the haiku as @haiku" do
        haiku = Haiku.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Haiku.any_instance.stub(:save).and_return(false)
        put :update, :id => haiku.id, :haiku => {}
        assigns(:haiku).should eq(haiku)
      end

      it "re-renders the 'edit' template" do
        haiku = Haiku.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Haiku.any_instance.stub(:save).and_return(false)
        put :update, :id => haiku.id, :haiku => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested haiku" do
      haiku = Haiku.create! valid_attributes
      expect {
        delete :destroy, :id => haiku.id
      }.to change(Haiku, :count).by(-1)
    end

    it "redirects to the haikus list" do
      haiku = Haiku.create! valid_attributes
      delete :destroy, :id => haiku.id
      response.should redirect_to(haikus_url)
    end
  end

end
