require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HaikuSearchesController do

  # This should return the minimal set of attributes required to create a valid
  # HaikuSearch. As you add validations to HaikuSearch, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all haiku_searches as @haiku_searches" do
      haiku_search = HaikuSearch.create! valid_attributes
      get :index
      assigns(:haiku_searches).should eq([haiku_search])
    end
  end

  describe "GET show" do
    it "assigns the requested haiku_search as @haiku_search" do
      haiku_search = HaikuSearch.create! valid_attributes
      get :show, :id => haiku_search.id
      assigns(:haiku_search).should eq(haiku_search)
    end
  end

  describe "GET new" do
    it "assigns a new haiku_search as @haiku_search" do
      get :new
      assigns(:haiku_search).should be_a_new(HaikuSearch)
    end
  end

  describe "GET edit" do
    it "assigns the requested haiku_search as @haiku_search" do
      haiku_search = HaikuSearch.create! valid_attributes
      get :edit, :id => haiku_search.id
      assigns(:haiku_search).should eq(haiku_search)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HaikuSearch" do
        expect {
          post :create, :haiku_search => valid_attributes
        }.to change(HaikuSearch, :count).by(1)
      end

      it "assigns a newly created haiku_search as @haiku_search" do
        post :create, :haiku_search => valid_attributes
        assigns(:haiku_search).should be_a(HaikuSearch)
        assigns(:haiku_search).should be_persisted
      end

      it "redirects to the created haiku_search" do
        post :create, :haiku_search => valid_attributes
        response.should redirect_to(HaikuSearch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved haiku_search as @haiku_search" do
        # Trigger the behavior that occurs when invalid params are submitted
        HaikuSearch.any_instance.stub(:save).and_return(false)
        post :create, :haiku_search => {}
        assigns(:haiku_search).should be_a_new(HaikuSearch)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HaikuSearch.any_instance.stub(:save).and_return(false)
        post :create, :haiku_search => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested haiku_search" do
        haiku_search = HaikuSearch.create! valid_attributes
        # Assuming there are no other haiku_searches in the database, this
        # specifies that the HaikuSearch created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HaikuSearch.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => haiku_search.id, :haiku_search => {'these' => 'params'}
      end

      it "assigns the requested haiku_search as @haiku_search" do
        haiku_search = HaikuSearch.create! valid_attributes
        put :update, :id => haiku_search.id, :haiku_search => valid_attributes
        assigns(:haiku_search).should eq(haiku_search)
      end

      it "redirects to the haiku_search" do
        haiku_search = HaikuSearch.create! valid_attributes
        put :update, :id => haiku_search.id, :haiku_search => valid_attributes
        response.should redirect_to(haiku_search)
      end
    end

    describe "with invalid params" do
      it "assigns the haiku_search as @haiku_search" do
        haiku_search = HaikuSearch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HaikuSearch.any_instance.stub(:save).and_return(false)
        put :update, :id => haiku_search.id, :haiku_search => {}
        assigns(:haiku_search).should eq(haiku_search)
      end

      it "re-renders the 'edit' template" do
        haiku_search = HaikuSearch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HaikuSearch.any_instance.stub(:save).and_return(false)
        put :update, :id => haiku_search.id, :haiku_search => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested haiku_search" do
      haiku_search = HaikuSearch.create! valid_attributes
      expect {
        delete :destroy, :id => haiku_search.id
      }.to change(HaikuSearch, :count).by(-1)
    end

    it "redirects to the haiku_searches list" do
      haiku_search = HaikuSearch.create! valid_attributes
      delete :destroy, :id => haiku_search.id
      response.should redirect_to(haiku_searches_url)
    end
  end

end
